spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD}
  jpa:
    show-sql: true
server:
  port: 5000    
management:
endpoints:
  web:
    exposure:
      include: health,info
endpoint:
  health:
    probes:
      enabled: true  
websiteUrl: https://store.com    